name: publish
on: workflow_dispatch
jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.2.4'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}
      - run: |
          # build the latest changes
          cabal new-install
          cabal new-run alyata-blog rebuild

          # setup default credentials
          git config user.name github-actions
          git config user.email github-actions@github.com

          # switch to master branch
          git fetch origin
          git checkout -B master --track origin/master

          # override the existing files in master with the fresh output
          rsync -a --filter='P _site/'      \
                   --filter='P _cache/'     \
                   --filter='P .git/'       \
                   --filter='P .gitignore'  \
                   --filter='P .stack-work' \
                   --delete-excluded        \
                   _site/ .

          # commit
          git add -A
          git commit -m "Publish"

          # push
          git push --set-upstream origin master
